/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "index": {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "style": {
    name: "style",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "music-player": {
    name: "music-player",
    description: "A music player with form and image.",
    type: "registry:block",
    registryDependencies: ["button","card","input","label"],
    files: [{
      path: "registry/audio-components/blocks/music-player/page.tsx",
      type: "registry:page",
      target: "app/music/page.tsx"
    },{
      path: "registry/audio-components/blocks/music-player/components/music-player.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/audio-components/blocks/music-player/page")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["music"],
    meta: undefined,
  },
  }