/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from 'react';

export const Index: Record<string, any> = {
  index: {
    name: 'index',
    description: '',
    type: 'registry:style',
    registryDependencies: ['utils'],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  style: {
    name: 'style',
    description: '',
    type: 'registry:style',
    registryDependencies: ['utils'],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  'dashboard-01': {
    name: 'dashboard-01',
    description: 'A dashboard with sidebar, charts and data table.',
    type: 'registry:block',
    registryDependencies: [
      'sidebar',
      'breadcrumb',
      'separator',
      'label',
      'chart',
      'card',
      'select',
      'tabs',
      'table',
      'toggle-group',
      'badge',
      'button',
      'checkbox',
      'dropdown-menu',
      'drawer',
      'input',
      'avatar',
      'sheet',
      'sonner',
    ],
    files: [
      {
        path: 'registry/new-york-v4/blocks/dashboard-01/page.tsx',
        type: 'registry:page',
        target: 'app/dashboard/page.tsx',
      },
      {
        path: 'registry/new-york-v4/blocks/dashboard-01/data.json',
        type: 'registry:file',
        target: 'app/dashboard/data.json',
      },
      {
        path: 'registry/new-york-v4/blocks/dashboard-01/components/app-sidebar.tsx',
        type: 'registry:component',
        target: '',
      },
      {
        path: 'registry/new-york-v4/blocks/dashboard-01/components/nav-main.tsx',
        type: 'registry:component',
        target: '',
      },
      {
        path: 'registry/new-york-v4/blocks/dashboard-01/components/nav-secondary.tsx',
        type: 'registry:component',
        target: '',
      },
      {
        path: 'registry/new-york-v4/blocks/dashboard-01/components/nav-user.tsx',
        type: 'registry:component',
        target: '',
      },
      {
        path: 'registry/new-york-v4/blocks/dashboard-01/components/section-cards.tsx',
        type: 'registry:component',
        target: '',
      },
      {
        path: 'registry/new-york-v4/blocks/dashboard-01/components/site-header.tsx',
        type: 'registry:component',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        '@/registry/new-york-v4/blocks/dashboard-01/page.tsx'
      );
      const exportName =
        Object.keys(mod).find(
          key => typeof mod[key] === 'function' || typeof mod[key] === 'object',
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ['dashboard'],
    meta: { iframeHeight: '1000px' },
  },
};
